# Generated by Django 4.1.7 on 2023-02-26 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Django_App', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='role',
        ),
    ]
