# Generated by Django 4.1.7 on 2023-02-26 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Django_App', '0002_remove_profile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='adult',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Django_App.adultincharge'),
        ),
    ]
