# Generated by Django 4.1.7 on 2023-02-26 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Django_App', '0005_alter_student_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adultincharge',
            name='adult',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Django_App.profile'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Django_App.profile'),
        ),
    ]
