# Generated by Django 4.1.7 on 2023-02-27 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Django_App', '0006_alter_adultincharge_adult_alter_teacher_teacher'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='adultInCharge',
            new_name='adult_in_charge',
        ),
    ]
